### PR TITLE
Events Page, Projects Page, Contact Us Page

### LINKED ISSUE #3: Add New Events Page
### **Tasks**
- Add a new page called **"Events.tsx"** and place it inside the **Components** folder
- Link the **New** Events Page to the Navbar option 'Events'
- For **Events page,** please use the placeholder photo called "placeholder-grey" as we do not have current events right now

**Routers**
- In HTML, we can simply go to a new page by adding the HTML link we want to go to once we click a button, in React it works a lot differently
- We need to import **routers** and **links** in order to implement and traverse through different pages
    - **To be able to do this, please install it through “npm install react-router-dom”**
- Look at App.tsx to see how these routers work for Home Page and About Page and look at Navbar.tsx to see how **“Link”** works when the user clicks one of these Navbar options
- Mimic this behavior for **Event** option in the navbar

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include **alt text** to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b add-events-page' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**PLEASE KEEP IN MIND** that when you create this new page, that it will have to become mobile-friendly. Therefore, when making this page for medium to large devices, delegate which commands you see fit that should have md: or lg: in front of it because they will most likely not be mobile-friendly.

### LINKED ISSUE #12: Add New Contact Page
### Tasks
- Add a new page with our contact information called **"Contact.tsx"** in the **Components** folder
- **Link** the New Contact Page to the Navbar option 'Contact'
- Use ‘font-jersey’ for ‘Contact’ which you can see in tailwind.config.js
- Use Discord, Instagram, and LinkedIn icons (Use **Navbar.tsx** as reference)
- Email is a ‘mail-to’ link to contact

**Routers**
- In HTML, we can simply go to a new page by adding the HTML link we want to go to once we click a button, in React it works a lot differently
- We need to import **routers** and **links** in order to implement and traverse through different pages
    - **To be able to do this, please install it through “npm install react-router-dom”**
- Look at App.tsx to see how these routers work for Home Page and About Page and look at Navbar.tsx to see how **“Link”** works when the user clicks one of these Navbar options
- Mimic this behavior for **Event** option in the navbar

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include **alt text** to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b add-events-page' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**PLEASE KEEP IN MIND** that when you create this new page, that it will have to become mobile-friendly. Therefore, when making this page for medium to large devices, delegate which commands you see fit that should have md: or lg: in front of it because they will most likely not be mobile-friendly.

### LINKED ISSUE #13: Mobile Friendly: Contact Page
### Tasks:
- Make Contact.tsx file Mobile Friendly

**Mobile Help**
In Tailwind, if you prefix a command such as "md:bg-transparent", this will make the background transparent for only medium to large devices. Therefore, if you have a combination of "bg-white md:bg-transparent" you will have a **white** background for mobile and **transparent** background for medium to large devices. Use combinations of commands like these so you have a working and a pleasing looking interface for both mobile and computer usage. _Please reference Navbar.tsx if you would like to see an example._

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include alt text to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b mobile-contact-footer' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**Regarding Repeating Color and Fonts**
- When using certain repetitive blues or fonts, please check ‘tailwind.config.js’ to see pre-made fonts you can call in your Tailwind lines to avoid long code
    - Ex. Instead of doing `bg-[#294B7B]` to make a blue backgrond, you can just do ‘bg-dark-blue’ because in tailwind.config.js there is a color called **dark-blue** with an already implemented hex value!

### LINKED ISSUE #16: Mobile Friendly: Events Page
### Tasks:
- Make Events.tsx file Mobile Friendly

**Mobile Help**
In Tailwind, if you prefix a command such as "md:bg-transparent", this will make the background transparent for only medium to large devices. Therefore, if you have a combination of "bg-white md:bg-transparent" you will have a **white** background for mobile and **transparent** background for medium to large devices. Use combinations of commands like these so you have a working and a pleasing looking interface for both mobile and computer usage. _Please reference Navbar.tsx if you would like to see an example._

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include alt text to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b mobile-friendly-events' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**Regarding Repeating Color and Fonts**
- When using certain repetitive blues or fonts, please check ‘tailwind.config.js’ to see pre-made fonts you can call in your Tailwind lines to avoid long code
    - Ex. Instead of doing `bg-[#294B7B]` to make a blue backgrond, you can just do ‘bg-dark-blue’ because in tailwind.config.js there is a color called **dark-blue** with an already implemented hex value!

### LINKED ISSUE #17: Add New Projects Page
### Tasks
- Add a new page with outside resource information called **"Projects.tsx"** in the **Components** folder
- **Link** the New Projects Page to the Navbar option 'Projects'
- Have the Tags ‘**AI’** and ‘**Open Source’**
- Make sure it has appropriate spacing
   - **Please follow the Figma to see which images and feautues you need to add**

**Routers**
- In HTML, we can simply go to a new page by adding the HTML link we want to go to once we click a button, in React it works a lot differently
- We need to import **routers** and **links** in order to implement and traverse through different pages
    - **To be able to do this, please install it through “npm install react-router-dom”**
- Look at App.tsx to see how these routers work for Home Page and About Page and look at Navbar.tsx to see how **“Link”** works when the user clicks one of these Navbar options
- Mimic this behavior for **Event** option in the navbar

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include **alt text** to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b add-resources-page' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**PLEASE KEEP IN MIND** that when you create this new page, that it will have to become mobile-friendly. Therefore, when making this page for medium to large devices, delegate which commands you see fit that should have md: or lg: in front of it because they will most likely not be mobile-friendly.

### LINKED ISSUE #18: Mobile Friendly: Projects Page
### Tasks:
- Make Projects.tsx file Mobile Friendly

**Mobile Help**
In Tailwind, if you prefix a command such as "md:bg-transparent", this will make the background transparent for only medium to large devices. Therefore, if you have a combination of "bg-white md:bg-transparent" you will have a **white** background for mobile and **transparent** background for medium to large devices. Use combinations of commands like these so you have a working and a pleasing looking interface for both mobile and computer usage. _Please reference Navbar.tsx if you would like to see an example._

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include alt text to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b mobile-friendly-events' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**Regarding Repeating Color and Fonts**
- When using certain repetitive blues or fonts, please check ‘tailwind.config.js’ to see pre-made fonts you can call in your Tailwind lines to avoid long code
    - Ex. Instead of doing `bg-[#294B7B]` to make a blue backgrond, you can just do `bg-dark-blue` because in tailwind.config.js there is a color called **dark-blue** with an already implemented hex value!

### PR DESCRIPTION
**Pull request by Priyansh4444**
Fixing an error on the navbar showing up on lg screens, 
Fixing Committees (though already fixed in another pr)
Running format on About Us
Linking pages to Apps.tsx

The formatting of the css needs to be checked since my screeen width is weird by defualt (not 16:9) so will need someone to check the spacing and adjust accordingly but it looks good on my device!

### CODE REVIEW

**Comment by margoglvz** [comment]
Thank you for all your quick work and effort! A lot of great additions! Although, I think some placements need to be fixed at least for what I see on my side. For some reason the Events Page is looking like this for me right now but it might just be a footer issue. And when it is mobile, the navbar is not completely hidden but it is only for the Projects Page. I'll look at it right now to see if I can help fix these issues but thank you again for your effort! 
image 
image

**Comment by margoglvz** [comment]
> Thank you for all your quick work and effort! A lot of great additions!...

okay i found out about the footer spacing :D

**Comment by Priyansh4444** [comment]
if need help lmk, i can get back on it before the break ends!

**Comment by margoglvz** [comment]
Thank you so much! The footer is mobile responsive now :D I'll work on why the navbar is being weird on the mobile side. For now can you look at the Contact Us Page? On my side there is this gap under the footer and when regarding mobile responsiveness, the Title is not visible on the screen. I'll commit my changes to this branch rn. Thank you!

**Comment by margoglvz** [comment]
My recent commits consisted of 
- Responsive Footer
- Added Footer tag below div tag in Events page so there is no gap

**Comment by Priyansh4444** [comment]
wait did you push your responsive footer commit? 
i kinda made a responsive footer as well :P, you can push force your commit in case of merge conflicts for the footer

**Comment by margoglvz** [comment]
omg bruh im so sorry i dont think i pushed, imma push rn

**Comment by margoglvz** [comment]
im just gonna resolve the merge conflicts and then push everything rn.

everything is pushed now sorry about that 🥲

**Comment by Priyansh4444** [comment]
Should Close #18, #17, #16, #13, #12, #3

**Comment by margoglvz** [comment]
hi! i pulled all the recent changes and the title on the Contact Us page for mobile is still above the navbar. I'll look at it right to see if I can fix it but other than that everything looks great!

**Comment by margoglvz** [comment]
its fixed now! ill resolve the git issue!! :DDDD

**Pull request merged**
