### PR TITLE
hero section made mobile friendly

### PR DESCRIPTION
**Pull request by NoNathan17**
- the dna background image looked weird on mobile screens so i just made the image in the top right of the background, i THINK it looks fine but someone should check on it and maybe find a way to fix that
- i changed the height of this section from h-screen to h-auto since there was a bunch of white space under the get involved button on mobile screens
- overall just made the text smaller to fit the smaller screen and changed some of the padding for mobile
- i was also looking at how the site would look on larger screens and like the background image kinda interferes with the navbar so that may be a future thing to fix

### CODE REVIEW

**Comment by NoNathan17** [comment]
i just saw the figma design LOL i will change it to look like that

**Comment by NoNathan17** [comment]
i think it should be all good now in accordance to the figma! 👍

**Comment by margoglvz** [comment]
haha thank you for your work! ill look at it rn!

**Comment by margoglvz** [comment]
it looks great!!! Also, I'm sorry but I realized I did not write about making AboutUs.tsx and Events.tsx file in the components folder also mobile friendly in the Git Issue in order to make the entire home page mobile friendly. Are you able to work on those 2 files as well? If not, I can also work on them this week just lmk! thank you!

**Comment by NoNathan17** [comment]
oh yeah i can work on those fs. ill probably get everything done within the next couple of days

**Comment by NoNathan17** [comment]
about and event section should be all mobile friendly now!

**Pull request closed without merging**
