### PR TITLE
Resources Page and Home Page mobile friendly!

### LINKED ISSUE #5: Mobile Friendly: Home Page
### Tasks:
- Make HeroSection.tsx mobile friendly
- Make AboutUs.tsx in Components Folder mobile friendly
- Make Events.tsx in Components Folder mobile friendly

**Mobile Help**
In Tailwind, if you prefix a command such as "md:bg-transparent", this will make the background transparent for only medium to large devices. Therefore, if you have a combination of "bg-white md:bg-transparent" you will have a **white** background for mobile and **transparent** background for medium to large devices. Use combinations of commands like these so you have a working and a pleasing looking interface for both mobile and computer usage. 

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include alt text to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b add-events-page' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**Regarding Repeating Color and Fonts**
- When using certain repetitive blues or fonts, please check ‘tailwind.config.js’ to see pre-made fonts you can call in your Tailwind lines to avoid long code
    - Ex. Instead of doing `bg-[#294B7B]` to make a blue backgrond, you can just do ‘bg-dark-blue’ because in tailwind.config.js there is a color called **dark-blue** with an already implemented hex value!

### LINKED ISSUE #14: Add New Resources Page
### Tasks
- Add a new page with outside resource information called **"Resources.tsx"** in the **Components** folder
- **Link** the New Resources Page to the Navbar option 'Resources'
- Have the Tags ‘**AI’** and ‘**Research Inspired’**
- Make sure it has appropriate spacing
- **How to Get the White Arrow from Figma**
    - Click on the White Arrow on Figma and select the dropdown option on the left
    - Choose ‘Vector’ on the left
    - Click on ‘Export’ on the right and download it as an **SVG**

**Routers**
- In HTML, we can simply go to a new page by adding the HTML link we want to go to once we click a button, in React it works a lot differently
- We need to import **routers** and **links** in order to implement and traverse through different pages
    - **To be able to do this, please install it through “npm install react-router-dom”**
- Look at App.tsx to see how these routers work for Home Page and About Page and look at Navbar.tsx to see how **“Link”** works when the user clicks one of these Navbar options
- Mimic this behavior for **Event** option in the navbar

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include **alt text** to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b add-resources-page' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**PLEASE KEEP IN MIND** that when you create this new page, that it will have to become mobile-friendly. Therefore, when making this page for medium to large devices, delegate which commands you see fit that should have md: or lg: in front of it because they will most likely not be mobile-friendly.

### LINKED ISSUE #15: Mobile Friendly: Resources Page
### Tasks:
- Make Resources.tsx file Mobile Friendly

**Mobile Help**
In Tailwind, if you prefix a command such as "md:bg-transparent", this will make the background transparent for only medium to large devices. Therefore, if you have a combination of "bg-white md:bg-transparent" you will have a **white** background for mobile and **transparent** background for medium to large devices. Use combinations of commands like these so you have a working and a pleasing looking interface for both mobile and computer usage. _Please reference Navbar.tsx if you would like to see an example._

**Images**
Since our club is centered around Health Technology, we prioritize inclusivity in everything we do. In the future, we will try to make this website more accessible but for now, all images on our website should include alt text to support individuals with visual impairments. Thank you!

**Branches**
Please make a new branch that is named your issue to work on,to make your commits as it will not be to main. For example you can do 'git checkout -b mobile-friendly-contact' to make a new branch of this name and switch to it at the same time. You can double check you are in the branch using 'git status'.

**Regarding Repeating Color and Fonts**
- When using certain repetitive blues or fonts, please check ‘tailwind.config.js’ to see pre-made fonts you can call in your Tailwind lines to avoid long code
    - Ex. Instead of doing `bg-[#294B7B]` to make a blue backgrond, you can just do ‘bg-dark-blue’ because in tailwind.config.js there is a color called **dark-blue** with an already implemented hex value!

### PR DESCRIPTION
**Pull request by NoNathan17**
- created the resources page and linked it to the navbar
- this branch was also merged with "17_projects_page" branch so it should be all up to date unless you guys made any changes that weren't pushed to that branch
- it looks good on my device but let me know if anything is acting up for you guys or youve got any suggestions 🙏

### CODE REVIEW

**Comment by NoNathan17** [comment]
also an easter egg if you click on the linktree button 😼

**Comment by NoNathan17** [comment]
closed the other pull request since this one has those changes as well

**Comment by margoglvz** [comment]
OOO OKAY IM EXCITED 🤩 GIT PULLING NOW

**Comment by margoglvz** [comment]
the home page looks great on mobile!!! :D i dont see anything when i click on the linktree tho 😭

**Comment by NoNathan17** [comment]
YAY OKAY! i meant the text on the resources page also 😭 i didnt change anything with the icon in the navbar

**Comment by margoglvz** [comment]
OHHH okay lemme check rn :D

**Comment by margoglvz** [comment]
SPENCER LAMM?!?!?!?!

**Comment by margoglvz** [comment]
AHAHA THATS GOOODDDD

**Comment by NoNathan17** [comment]
the legend himself 😎

**Comment by Priyansh4444** [comment]
MY GOAT SPENCER

**Comment by margoglvz** [comment]
everything looks great!! thats another git issue resolved 😎 also i adjusted some spacing so now all of the hero section fits onto mobile screen at the start! :D

**Comment by margoglvz** [comment]
k nevermind it kinda looks bad on some other screens imma leave it as is 😃

**Comment by Priyansh4444** [comment]
i can fix if it looks bad, whats the issue

**Comment by margoglvz** [comment]
oo well i was doing h-svh so that it fits all in one screen but when the screen is too small sometimes the text spills to the next component and if its like an ipad or something then there is too much white space. i tried to mess around with the text sizes and stuff but nothing looked right.

**Pull request merged**
